name: CI

on:
  push:
  pull_request:

jobs:
  StaticAnalysis:
    name: StaticAnalysis (PHP ${{ matrix.php }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        php:
          - 8.1
          - 8.2
    steps:
      - uses: actions/checkout@v2
      - name: Install Meson and Linux Deps
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install meson ninja
          sudo apt-get update -y
          sudo apt-get install -y libgtk-3-dev xvfb
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ardillo-ardillo-php/ext@seed0
      - name: Install dependencies
        run: composer install
      - name: Run PHPStan
        run: composer phpstan
      - name: Run Psalm
        run: composer psalm -- --output-format=github
