name: CI

on:
  push:
  pull_request:

jobs:
  static-analysis-linux:
    name: Static Analysis (PHP ${{ matrix.php }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        php:
          - 8.2
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: extension=ardillo
      - name: Prepare environment
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install meson ninja
          sudo apt-get update -y
          sudo apt-get install -y libgtk-3-dev
          git clone https://github.com/ardillo-php/ext.git
          cd ext && git submodule update --init && phpize && ./configure && make -j && sudo make install && cd ..
          sudo ldconfig
          sudo ldconfig -p
          ls -al /usr/lib/php/20220829/ardillo.so
          pkg-config --cflags --libs gtk+-3.0
          ldd /usr/lib/php/20220829/ardillo.so
      - name: Install Composer dependencies
        run: composer install
      - name: tmate session if tests fail
        if: failure() && github.event_name == 'workflow_dispatch'
        uses: mxschmitt/action-tmate@v3
      - name: Run Static Analysis
        run: |
          composer phpstan
          composer psalm -- --output-format=github
